Repository mariusz-ostoja-swierczynski/tech-controllers, pull requests merged in 2024-10, with the labels that each got.

#125 :sparkles: Add zone alarm state
  custom_components/tech/const.py
  custom_components/tech/sensor.py
  custom_components/tech/strings.json
  custom_components/tech/translations/cs.json
  custom_components/tech/translations/de.json
  custom_components/tech/translations/en.json
  custom_components/tech/translations/es.json
  custom_components/tech/translations/et.json
  custom_components/tech/translations/fr.json
  custom_components/tech/translations/hr.json
  custom_components/tech/translations/hu.json
  custom_components/tech/translations/it.json
  custom_components/tech/translations/lt.json
  custom_components/tech/translations/nl.json
  custom_components/tech/translations/pl.json
  custom_components/tech/translations/ro.json
  custom_components/tech/translations/ru.json
  custom_components/tech/translations/si.json
  custom_components/tech/translations/sk.json
Labels: feature, major

#126 Fix API tests compatibility with win32 platform.
  tests/tests_api/__init__.py
Labels: chore

#128 Bump dependencies
  custom_components/tech/config_flow.py
  hacs.json
  requirements.txt
  requirements_test.txt
  requirements_test_api.txt
  ruff.toml
  tests/tests_api/__init__.py
Labels: bug, minor
