Repository mariusz-ostoja-swierczynski/tech-controllers, pull requests merged in 2024-04, with the labels that each got.

#72 add target_temperature_step
  custom_components/tech/climate.py
Labels: bug, minor

#74 add working device
  README.md
Labels: documentation, minor

#73 update minimum and maximum allowed temp
  custom_components/tech/climate.py
Labels: feature, minor

#75 adding openapi specification link to tech controllers
  README.md
Labels: documentation, minor

#78 fix bug-33
  custom_components/tech/tech.py
Labels: bug, minor

#79 fix permissions
  scripts/develop
  scripts/lint
  scripts/setup
Labels: minor, chore

#80 Small tuning of different things
  .devcontainer.json
  .github/scripts/update_hacs_manifest.py
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  custom_components/tech/__init__.py
  custom_components/tech/assets.py
  custom_components/tech/binary_sensor.py
  custom_components/tech/climate.py
  custom_components/tech/config_flow.py
  custom_components/tech/entity.py
  custom_components/tech/sensor.py
  custom_components/tech/tech.py
  images/ha-tech-1.png
  images/ha-tech-2.png
  images/ha-tech-add-integration-1.png
  images/ha-tech-add-integration-2.png
  images/ha-tech-add-integration-3.png
  images/ha-tech-add-integration-4.png
  images/ha-tech-add-integration.png
  images/ha-tech-devices.png
  images/ha-tech-logs-ex.png
  images/ha-tech-logs-ex2.png
  images/ha-tech-logs-ex3.png
  images/ha-tech-logs.png
  requirements.txt
  tests/common.py
  tests/tests_api/conftest.py
  tests/tests_api/test_api.py
Labels: minor, chore

#81 update ruff config and fix some linting issues
  custom_components/tech/climate.py
  custom_components/tech/config_flow.py
  custom_components/tech/sensor.py
  ruff.toml
Labels: chore

#83 ✨ Update device and entity naming
  custom_components/tech/binary_sensor.py
  custom_components/tech/climate.py
  custom_components/tech/config_flow.py
  custom_components/tech/const.py
  custom_components/tech/entity.py
  custom_components/tech/sensor.py
  custom_components/tech/strings.json
  custom_components/tech/translations/en.json
  custom_components/tech/translations/pl.json
  custom_components/tech/translations/sk.json
Labels: feature, minor

#85 :bug: Improve error conditions in config flow. Fixes #84
  custom_components/tech/config_flow.py
  custom_components/tech/strings.json
  custom_components/tech/translations/en.json
  custom_components/tech/translations/pl.json
  custom_components/tech/translations/sk.json
Labels: bug
