Repository mariusz-ostoja-swierczynski/tech-controllers, pull requests merged in 2024-09, with the labels that each got.

#108 some minor code improvments
  custom_components/tech/__init__.py
  custom_components/tech/assets.py
  custom_components/tech/climate.py
  custom_components/tech/config_flow.py
  custom_components/tech/tech.py
  requirements.txt
  requirements_test.txt
  requirements_test_api.txt
  tests/tests_api/test_api.py
Labels: minor, chore

#111 :bug: Fix wrong link in bug report
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: bug, documentation, minor

#113 :bug: Fix missing atttributes in some sensors
  custom_components/tech/sensor.py
Labels: bug, minor

#114 chore: move to f strings
  custom_components/tech/tech.py
Labels: minor, chore

#115 chore: update dependencies
  requirements.txt
  requirements_test.txt
  requirements_test_api.txt
Labels: minor, chore

#116 🚨 Satisfy Ruff and Pylint
  custom_components/tech/__init__.py
  custom_components/tech/assets.py
  custom_components/tech/binary_sensor.py
  custom_components/tech/climate.py
  custom_components/tech/config_flow.py
  custom_components/tech/const.py
  custom_components/tech/coordinator.py
  custom_components/tech/entity.py
  custom_components/tech/sensor.py
  custom_components/tech/tech.py
  tests/tests_api/test_api.py
Labels: minor, chore
