Repository mariusz-ostoja-swierczynski/tech-controllers, pull requests merged in 2025-01, with the labels that each got.

#142 ✨ minor changes like linting, tooling and Readme
  .pre-commit-config.yaml
  README.md
  custom_components/tech/const.py
  custom_components/tech/sensor.py
  custom_components/tech/tech.py
  tests/tests_api/__init__.py
Labels: documentation, chore

#146 Create pt.json
  custom_components/tech/translations/pt.json
Labels: chore

#147 Add nix devenv
  .envrc
  .gitignore
  CONTRIBUTING.md
  devenv.lock
  devenv.nix
  devenv.yaml
Labels: chore

#149 Update sensor.py
  custom_components/tech/sensor.py
Labels: bug
